---
- name: Generate an SSL certificate and a key
  shell: "openssl req -x509 -nodes -days 1825 -newkey rsa:2048 -keyout {{
    apache_ssl_cert_key_path }}/{{ apache_ssl_cert_filename }}.key -out {{
    apache_ssl_cert_path }}/{{ apache_ssl_cert_filename }}.crt -subj \"/C={{
    apache_ssl_cert_country }}/ST={{ apache_ssl_cert_state }}/L={{
    apache_ssl_cert_city }}/O={{ apache_ssl_cert_org }}/OU={{
    apache_ssl_cert_ou }}/CN={{ apache_ssl_cert_cn }}/emailAddress={{
    apache_ssl_cert_email }}\""
  register: openssl

- debug:
    var: openssl

- name: Set modes for the key
  file:
    path: "{{ apache_ssl_cert_key_path }}/{{ apache_ssl_cert_filename }}.key"
    mode: 0600
