---
- name: Install packages
  yum:
    name: "{{ mariadb_packages }}"
    state: present
  notify: Reload mariadb

- name: Enable the service
  service:
    name: "{{ mariadb_unit_name }}"
    enabled: true

- name: Flush handlers
  meta: flush_handlers

- import_tasks: mariadb-users.yml
  when: mariadb_users_create
